export type WorkflowAuditState = "mapped" | "attention" | "boundary" | "gap";

export type WorkflowFlow = {
  id: string;
  name: string;
  shortName: string;
  description: string;
  userGoal: string;
  accent: string;
};

export type WorkflowStep = {
  id: string;
  flowId: string;
  order: number;
  title: string;
  surface: "page" | "dialog" | "full-screen workflow" | "CLI / evaluation";
  route?: string;
  userSees: string;
  primaryAction: string;
  outcome: string;
  assertions: string[];
  writes?: string[];
  auditState: WorkflowAuditState;
  auditNote?: string;
};

export type WorkflowConnection = {
  source: string;
  target: string;
  label: string;
};

export const WORKFLOW_FLOWS: WorkflowFlow[] = [
  {
    id: "lab-entry",
    name: "Lab entry and first-run setup",
    shortName: "Lab entry",
    description: "Authentication, lab membership, initial cohort creation, and arrival at useful work.",
    userGoal: "Get into the correct lab context and reach a useful first task without contaminating another lab's records.",
    accent: "#4f46e5",
  },
  {
    id: "daily-observation",
    name: "Single AI-assisted observation",
    shortName: "Single observation",
    description: "One external photograph from capture through exact-stage AI proposal and reviewed record.",
    userGoal: "Turn one mouse photograph into a traceable prediction, then accept, correct, or mark it uncertain.",
    accent: "#0369a1",
  },
  {
    id: "batch-session",
    name: "Batch capture and review session",
    shortName: "Batch session",
    description: "Configure a session, upload several images, review every suggestion, and save a receipt.",
    userGoal: "Process a daily cohort efficiently without allowing unreviewed model output into the lab record.",
    accent: "#0f766e",
  },
  {
    id: "evaluation",
    name: "Cytology-grounded model evaluation",
    shortName: "Model evaluation",
    description: "Check evidence readiness, export a manifest, run held-out inference, and inspect subgroup results.",
    userGoal: "Turn reviewed observations into a reproducible, leakage-resistant evaluation without exposing private images.",
    accent: "#7c3aed",
  },
  {
    id: "experiment",
    name: "Experiment organization and reporting",
    shortName: "Experiments",
    description: "Create an experiment, attach cohorts, inspect trends, and export an analysis package.",
    userGoal: "Organize longitudinal cohort work into a study-level view that is ready to discuss or export.",
    accent: "#c2410c",
  },
  {
    id: "administration",
    name: "Lab discovery, membership, and secondary surfaces",
    shortName: "Administration",
    description: "Find labs, request access, and manage membership and data ownership.",
    userGoal: "Understand where collaboration and administration live without dead-end primary destinations.",
    accent: "#475569",
  },
];

export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: "entry-sign-in",
    flowId: "lab-entry",
    order: 1,
    title: "Sign in or create account",
    surface: "page",
    route: "/sign-in",
    userSees: "Clerk authentication before any animal or lab data is shown.",
    primaryAction: "Authenticate",
    outcome: "A user session exists; no organization is assumed yet.",
    assertions: ["Authentication is the only primary task", "No research data is visible before authentication"],
    auditState: "boundary",
    auditNote: "The authentication UI is Clerk-owned and must be audited as an external boundary.",
  },
  {
    id: "entry-org-gate",
    flowId: "lab-entry",
    order: 2,
    title: "Resolve lab context",
    surface: "page",
    route: "/onboarding",
    userSees: "A lab-finder experience instead of Clerk's generic choose-organization task.",
    primaryAction: "Join an existing lab or create one",
    outcome: "The user chooses a safe data-ownership context.",
    assertions: ["No-lab state is explicit", "Join and create paths are both discoverable"],
    auditState: "mapped",
  },
  {
    id: "entry-join-create",
    flowId: "lab-entry",
    order: 3,
    title: "Join request or new lab",
    surface: "dialog",
    route: "/onboarding",
    userSees: "A join-request message or a new-lab form with institution, description, and discoverability.",
    primaryAction: "Submit the selected path",
    outcome: "Membership is pending or a lab becomes active.",
    assertions: ["The data-sharing consequence is understandable", "Pending membership has a visible status"],
    writes: ["organization_profiles", "join_requests", "Clerk organization membership"],
    auditState: "attention",
    auditNote: "The two paths have materially different timing and permissions and need especially clear confirmation copy.",
  },
  {
    id: "entry-first-cohort",
    flowId: "lab-entry",
    order: 4,
    title: "Create the first cohort",
    surface: "full-screen workflow",
    route: "/dashboard",
    userSees: "A two-step mouse-estrus setup with cohort name, optional protocol note, the four saved stages, and the evaluation-relevant coat/strain contract.",
    primaryAction: "Create the mouse cohort",
    outcome: "The first mouse research container exists.",
    assertions: ["Generic cell, plant, and wound templates do not compete with the app's core purpose", "Required and optional fields are explicit", "The saved-stage contract is visible before creation"],
    writes: ["cohorts"],
    auditState: "mapped",
    auditNote: "The local redesign removes the generic template chooser and configures mouse estrus tracking directly.",
  },
  {
    id: "entry-first-subjects",
    flowId: "lab-entry",
    order: 5,
    title: "Add mouse identities",
    surface: "page",
    route: "/cohorts/[id]#subjects",
    userSees: "A clear handoff to mouse ID, coat colour, and strain before any single or bulk image capture.",
    primaryAction: "Add subjects",
    outcome: "Images can be assigned to known subjects and subgroup metadata is available for later evaluation.",
    assertions: ["Bulk capture is not the first action for an empty cohort", "Subject identity precedes image assignment", "Coat colour and strain are visible evaluation inputs"],
    writes: ["mice"],
    auditState: "mapped",
  },
  {
    id: "entry-dashboard",
    flowId: "lab-entry",
    order: 6,
    title: "Arrive at the prediction inbox",
    surface: "page",
    route: "/dashboard",
    userSees: "Analyzed photographs grouped into ready to accept, needs attention, and AI abstained, with the exact-stage proposal and all four scores visible.",
    primaryAction: "Review the next AI proposal",
    outcome: "The scientist enters an exception-oriented review workflow.",
    assertions: ["Predictions outrank manual-entry prompts", "Pending proposals are separate from confirmed records", "All four scores are visible", "Bulk analysis remains available"],
    auditState: "mapped",
    auditNote: "The dashboard is now an AI prediction inbox; confirmed history remains behind progressive disclosure.",
  },

  {
    id: "single-cohort",
    flowId: "daily-observation",
    order: 1,
    title: "Open today's cohort work",
    surface: "page",
    route: "/cohorts/[id]",
    userSees: "Today's prediction workload, analyze-one and analyze-batch actions, plus confirmed records and research tools as secondary destinations.",
    primaryAction: "Analyze one observation or start a batch",
    outcome: "The task is scoped to one colony or study cohort.",
    assertions: ["Cohort identity is persistent", "AI analysis is the primary work", "The exact-stage model and independent binary guardrail are not conflated"],
    auditState: "mapped",
    auditNote: "The equal-weight destination grid was replaced with a daily checklist and progressive disclosure for historical data tools.",
  },
  {
    id: "single-subjects",
    flowId: "daily-observation",
    order: 2,
    title: "Choose the next mouse",
    surface: "page",
    route: "/cohorts/[id]#subjects",
    userSees: "Mice awaiting photographs first, recent reviewed stages, and missing research-metadata cues.",
    primaryAction: "Analyze observation",
    outcome: "The selected mouse opens directly into a subject-bound observation dialog.",
    assertions: ["Subject identity is unambiguous", "Already-recorded and due-today states are distinct", "Missing coat colour or strain is visible before evaluation"],
    auditState: "mapped",
  },
  {
    id: "single-record",
    flowId: "daily-observation",
    order: 3,
    title: "Inspect the subject record",
    surface: "page",
    route: "/subjects/[id]",
    userSees: "AI-generated stage history, accepted versus corrected proposals, cycle summary, research metadata, and an analyze-new-observation action.",
    primaryAction: "Analyze new observation",
    outcome: "The scientist begins a subject-specific AI analysis.",
    assertions: ["Subject name remains visible", "Historical evidence does not obscure the new-entry action"],
    auditState: "mapped",
  },
  {
    id: "single-image-contract",
    flowId: "daily-observation",
    order: 4,
    title: "Choose modality and image",
    surface: "dialog",
    route: "/subjects/[id]",
    userSees: "External-photo versus vaginal-cytology choice, original-image preview, interactive prepared-ROI framing, date, and optional protocol fields.",
    primaryAction: "Center the reviewed anatomy inside the exact model field",
    outcome: "The original observation and the model-input crop have an explicit, reproducible relationship.",
    assertions: ["Cytology cannot be sent to the external-photo model", "The preview never uses a hidden object-cover crop", "Zoom or pan clears ROI confirmation", "Required and optional fields are visually distinct"],
    writes: ["prepared ROI file", "crop coordinates and zoom", "capture metadata draft"],
    auditState: "mapped",
    auditNote: "The prior checkbox-only contract was replaced with an executable crop tool that exposes the frozen processor's center field.",
  },
  {
    id: "single-analysis-choice",
    flowId: "daily-observation",
    order: 5,
    title: "Run exact-stage analysis",
    surface: "dialog",
    route: "/subjects/[id]",
    userSees: "External photographs request an exact-stage proposal only after the prepared ROI is generated and confirmed; manual entry remains a fallback.",
    primaryAction: "Analyze estrus stage",
    outcome: "The model returns an exact-stage proposal with four relative support scores.",
    assertions: ["The generated ROI file, not the original frame, is sent to the model", "ROI confirmation precedes model use", "A model failure still leaves a manual recovery path"],
    auditState: "mapped",
  },
  {
    id: "single-review",
    flowId: "daily-observation",
    order: 6,
    title: "Review the exact-stage proposal",
    surface: "dialog",
    route: "/subjects/[id]",
    userSees: "The AI's proposed stage, all four relative support scores, image, subject context, and the independent early-versus-late guardrail.",
    primaryAction: "Accept the proposal or correct it",
    outcome: "The reviewed proposal becomes a traceable scientific record.",
    assertions: ["Exact-stage prediction is primary", "All four scores are visible", "Abstention and review flags are clear", "Corrections retain the original proposal"],
    auditState: "mapped",
    auditNote: "Redesigned around a primary exact-stage proposal with an independent binary guardrail and explicit override path.",
  },
  {
    id: "single-ground-truth",
    flowId: "daily-observation",
    order: 7,
    title: "Declare confirmation source",
    surface: "dialog",
    route: "/subjects/[id]",
    userSees: "A choice between external-photo visual review and paired vaginal cytology, with a required smear image for the latter.",
    primaryAction: "Choose evidence and acknowledge the saved stage",
    outcome: "Visual guesses cannot masquerade as cytology-grounded labels.",
    assertions: ["Paired cytology requirements are explicit", "The acknowledgement names the selected stage"],
    writes: ["ground_truth_source", "cytology reference upload", "reviewer confirmation"],
    auditState: "mapped",
  },
  {
    id: "single-saved",
    flowId: "daily-observation",
    order: 8,
    title: "Save the confirmed record",
    surface: "page",
    route: "/subjects/[id]",
    userSees: "The new observation in the subject timeline with original image, prepared model input, crop metadata, modality, provenance, and review evidence.",
    primaryAction: "Inspect or continue to the next observation",
    outcome: "A permanent, auditable lab record exists.",
    assertions: ["Saved stage and confirmation source are visible", "A failed save preserves the entered work"],
    writes: ["estrus_logs", "private image object", "optional cytology reference object"],
    auditState: "mapped",
  },

  {
    id: "batch-open",
    flowId: "batch-session",
    order: 1,
    title: "Open batch capture",
    surface: "page",
    route: "/cohorts/[id]/batch",
    userSees: "A dedicated full-screen workspace separated from cohort analytics.",
    primaryAction: "Start a new session",
    outcome: "The batch is bound to a cohort.",
    assertions: ["Cohort and session identity are visible", "Leaving the workflow has an understandable consequence"],
    auditState: "mapped",
  },
  {
    id: "batch-contract",
    flowId: "batch-session",
    order: 2,
    title: "Set session contract",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "Modality, capture date, session name, and protocol metadata before images enter analysis.",
    primaryAction: "Confirm external-photo batch settings",
    outcome: "All items inherit coherent provenance.",
    assertions: ["Cytology is explicitly unavailable in batch analysis", "Defaults are visible and editable"],
    auditState: "mapped",
  },
  {
    id: "batch-images",
    flowId: "batch-session",
    order: 3,
    title: "Add images",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "Drop zone, image queue, previews, and per-file validation.",
    primaryAction: "Choose or drop a set of photos",
    outcome: "Valid images enter a visible pending queue.",
    assertions: ["Rejected files explain why", "Image count and queue status are available without opening each item"],
    auditState: "mapped",
  },
  {
    id: "batch-propose-roi",
    flowId: "batch-session",
    order: 4,
    title: "Propose every ROI",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "An automatic square ROI suggestion for every original image, with obvious missing, low-quality, and outlier crops flagged.",
    primaryAction: "Let the crop proposal queue finish",
    outcome: "Each original has either a proposed model input or a named failure.",
    assertions: ["Original images are never overwritten", "A failed proposal cannot silently fall back to an unknown crop", "Proposal status is visible across the contact sheet"],
    auditState: "mapped",
    auditNote: "The local batch flow now proposes prepared ROIs before inference and keeps the original image immutable.",
  },
  {
    id: "batch-confirm-roi",
    flowId: "batch-session",
    order: 5,
    title: "Confirm the crop sheet",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "A contact sheet of suggested model fields, with exceptions grouped first and an original-versus-crop inspector for intervention.",
    primaryAction: "Confirm all acceptable crops, then adjust only exceptions",
    outcome: "Every analyzed item has a scientist-confirmed prepared ROI.",
    assertions: ["One action can accept all unflagged crops", "Zoom and pan are available per exception", "The exact model field is visible", "Changing a crop clears its confirmation"],
    auditState: "mapped",
    auditNote: "The local batch flow supports contact-sheet confirmation, one-action acceptance, and per-image crop intervention before analysis.",
  },
  {
    id: "batch-assign",
    flowId: "batch-session",
    order: 6,
    title: "Assign subjects",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "Each image paired to a known subject before a permanent record can be written.",
    primaryAction: "Match every photo to a mouse",
    outcome: "No batch item has ambiguous ownership.",
    assertions: ["Unassigned items are impossible to overlook", "Duplicate subject assignment is intentional rather than accidental"],
    auditState: "attention",
    auditNote: "Large cohorts and similar subject names are a likely operational error source.",
  },
  {
    id: "batch-analyze",
    flowId: "batch-session",
    order: 7,
    title: "Run the analysis queue",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "Per-image progress, failures, and returned evidence while the rest of the queue continues. Only confirmed prepared ROIs enter the model.",
    primaryAction: "Wait, retry a failure, or begin reviewing completed items",
    outcome: "Every item resolves to a suggestion, an abstention, or a named failure.",
    assertions: ["Progress is announced beyond colour alone", "One failed item cannot erase completed work"],
    auditState: "attention",
    auditNote: "Queue progress, partial failure, and retry behavior need live-session evidence before this state can be considered safe.",
  },
  {
    id: "batch-review",
    flowId: "batch-session",
    order: 8,
    title: "Review every item",
    surface: "full-screen workflow",
    route: "/cohorts/[id]/batch",
    userSees: "A prediction inbox grouped by ready, needs attention, and abstained, with focused image, exact-stage proposal, all four scores, and context.",
    primaryAction: "Accept or correct each AI proposal",
    outcome: "Only reviewed items become permanent logs.",
    assertions: ["Unreviewed and reviewed items are visibly different", "Keyboard and screen-reader users can move through the queue", "Corrections retain the original suggestion"],
    auditState: "attention",
    auditNote: "This is the highest-throughput and highest-risk scientist workflow.",
  },
  {
    id: "batch-receipt",
    flowId: "batch-session",
    order: 9,
    title: "Inspect the session receipt",
    surface: "page",
    route: "/scans/[sessionId]",
    userSees: "AI proposal versus scientist decision for every item, accepted and corrected counts, stage breakdown, images, subjects, and provenance.",
    primaryAction: "Resolve failures or return to the cohort",
    outcome: "The batch has a durable audit trail.",
    assertions: ["Completed, failed, and pending counts reconcile", "Re-analysis does not imply overwriting confirmed logs"],
    auditState: "mapped",
  },

  {
    id: "eval-open",
    flowId: "evaluation",
    order: 1,
    title: "Open evaluation readiness",
    surface: "page",
    route: "/cohorts/[id]#evaluation",
    userSees: "Evidence-quality checks within the cohort workspace.",
    primaryAction: "Inspect whether records can support an evaluation",
    outcome: "Collection gaps are visible before export.",
    assertions: ["The tab name matches evaluation intent", "Evaluation is not confused with filename QA"],
    auditState: "mapped",
    auditNote: "The local cohort workspace now opens a provenance-first readiness checklist; filename QA is explicitly legacy and collapsed.",
  },
  {
    id: "eval-coverage",
    flowId: "evaluation",
    order: 2,
    title: "Check evidence coverage",
    surface: "page",
    route: "/cohorts/[id]#evaluation",
    userSees: "Label provenance, paired cytology, subject coverage, class distribution, and missing metadata.",
    primaryAction: "Resolve missing pairings or metadata",
    outcome: "Only explicit cytology-grounded candidates advance.",
    assertions: ["Visual-review records are excluded clearly", "Readiness thresholds name both subjects and observations"],
    auditState: "mapped",
  },
  {
    id: "eval-export",
    flowId: "evaluation",
    order: 3,
    title: "Export the cohort manifest",
    surface: "page",
    route: "/cohorts/[id]",
    userSees: "A preflight-manifest action that downloads provenance, paired-cytology references, confirmed prepared ROI fields, and explicit binary-model evidence without permanent public image links.",
    primaryAction: "Download the manifest",
    outcome: "A reproducible handoff file leaves the app.",
    assertions: ["Export scope is clear before download", "Private object references remain private"],
    writes: ["local CSV download"],
    auditState: "boundary",
  },
  {
    id: "eval-preflight",
    flowId: "evaluation",
    order: 4,
    title: "Run grouped preflight",
    surface: "CLI / evaluation",
    userSees: "A structural report for pairings, subject overlap, coat-colour support, and a frozen split.",
    primaryAction: "Repair data or accept the generated train/test manifest",
    outcome: "An evaluation-ready, hash-bound records file exists.",
    assertions: ["No subject overlaps train and test", "The colour claim requires supported held-out groups"],
    writes: ["cytology-grounded-records.csv", "preflight JSON"],
    auditState: "boundary",
  },
  {
    id: "eval-inference",
    flowId: "evaluation",
    order: 5,
    title: "Run held-out inference",
    surface: "CLI / evaluation",
    userSees: "Exact app-policy predictions on test-only external photos; cytology images and labels are never model inputs.",
    primaryAction: "Generate one-to-one predictions",
    outcome: "Every held-out log has a prediction or abstention with reasons.",
    assertions: ["Training rows are skipped", "Acquisition and reference-domain evidence are retained"],
    writes: ["binary-heldout-predictions.csv", "inference report JSON"],
    auditState: "boundary",
  },
  {
    id: "eval-report",
    flowId: "evaluation",
    order: 6,
    title: "Audit subgroup results",
    surface: "CLI / evaluation",
    userSees: "Accuracy with abstentions counted incorrect, coverage, calibration metrics, clustered uncertainty, and coat/device/reviewer subgroups.",
    primaryAction: "Decide whether evidence is sufficient for another model promotion",
    outcome: "A colour claim is either supported narrowly or explicitly withheld.",
    assertions: ["Unsupported subgroup estimates are descriptive only", "The report preserves the real-coat limitation"],
    writes: ["subgroup evaluation report JSON"],
    auditState: "boundary",
  },

  {
    id: "experiment-list",
    flowId: "experiment",
    order: 1,
    title: "Open experiments",
    surface: "page",
    route: "/experiments",
    userSees: "Active and planned study workspaces, cohort counts, study windows, a clear create action, and completed studies behind disclosure.",
    primaryAction: "Open or create an experiment",
    outcome: "The scientist chooses a study-level container.",
    assertions: ["Mock data is absent from the scientist-facing surface", "Destructive actions are clearly separated", "Completed studies do not compete with current work"],
    auditState: "mapped",
    auditNote: "The local redesign removes the mock-data action, separates completed work, and moves deletion into a secondary action menu.",
  },
  {
    id: "experiment-create",
    flowId: "experiment",
    order: 2,
    title: "Create experiment",
    surface: "dialog",
    route: "/experiments",
    userSees: "A study name, optional question or note, and optional start/end dates, with the cohort-attachment sequence explained.",
    primaryAction: "Create the experiment",
    outcome: "An empty experiment workspace exists.",
    assertions: ["Optional and required fields are explicit", "End date cannot precede start date", "Submission has progress and error recovery"],
    writes: ["experiments"],
    auditState: "mapped",
  },
  {
    id: "experiment-attach",
    flowId: "experiment",
    order: 3,
    title: "Attach cohorts",
    surface: "page",
    route: "/experiments/[id]",
    userSees: "The current cohort scope, subject and record counts, paired-cytology coverage, and an explicit manage-scope action.",
    primaryAction: "Add the intended cohorts",
    outcome: "Study analytics derive from an explicit cohort set.",
    assertions: ["Already-attached cohorts cannot be duplicated", "Removing a cohort explains that source subjects and observations remain", "Study export scope matches the attached cohort set"],
    writes: ["experiment_cohorts"],
    auditState: "mapped",
  },
  {
    id: "experiment-report",
    flowId: "experiment",
    order: 4,
    title: "Inspect and export study",
    surface: "page",
    route: "/experiments/[id]",
    userSees: "A study summary led by collection coverage, missingness, confirmation state, cytology pairing, cohort scope, and bounded binary-model review evidence; cycle atlas and records remain one step away.",
    primaryAction: "Review the cycle atlas or export a provenance manifest",
    outcome: "The experiment can be discussed outside the capture workflow.",
    assertions: ["Cycle atlas names subject-day coverage and shows missing cells without inference", "Scientist stage, provenance, and binary review are separate columns", "Export content matches the selected experiment and uses object references rather than public image links"],
    writes: ["local provenance CSV download"],
    auditState: "mapped",
    auditNote: "The local redesign replaces generic KPI charts and confidence columns with study scope, collection integrity, an explicit missing-data atlas, provenance-first records, and a scoped export preflight.",
  },

  {
    id: "admin-discover",
    flowId: "administration",
    order: 1,
    title: "Discover labs",
    surface: "page",
    route: "/discover",
    userSees: "Search, institution filtering, lab profiles, and membership status.",
    primaryAction: "Inspect a lab and request access",
    outcome: "The user can collaborate beyond the active lab.",
    assertions: ["Active and discoverable labs are distinguishable", "The page does not expose private membership information"],
    auditState: "mapped",
  },
  {
    id: "admin-request",
    flowId: "administration",
    order: 2,
    title: "Request lab access",
    surface: "dialog",
    route: "/discover",
    userSees: "Selected lab identity, optional message, and pending-request feedback.",
    primaryAction: "Submit or cancel a request",
    outcome: "Membership remains pending until an administrator acts.",
    assertions: ["Duplicate requests are prevented visibly", "Cancellation scope is clear"],
    writes: ["join_requests"],
    auditState: "mapped",
  },
  {
    id: "admin-settings",
    flowId: "administration",
    order: 3,
    title: "Manage lab and profile settings",
    surface: "page",
    route: "/settings",
    userSees: "Personal settings, organization profile, discoverability, membership, and pending requests according to role.",
    primaryAction: "Update a setting or review access",
    outcome: "Lab identity and access stay current.",
    assertions: ["Role-limited controls explain why they are unavailable", "Saving has clear confirmation"],
    writes: ["organization_profiles", "membership decisions"],
    auditState: "attention",
    auditNote: "Role-dependent controls and organization-wide writes need explicit permission and confirmation evidence.",
  },
];

export const WORKFLOW_CONNECTIONS: WorkflowConnection[] = WORKFLOW_FLOWS.flatMap(
  (flow) => {
    const steps = WORKFLOW_STEPS.filter((step) => step.flowId === flow.id).sort(
      (left, right) => left.order - right.order
    );
    return steps.slice(1).map((step, index) => ({
      source: steps[index].id,
      target: step.id,
      label: steps[index].primaryAction,
    }));
  }
);

export function workflowFlow(flowId: string): WorkflowFlow {
  const flow = WORKFLOW_FLOWS.find((candidate) => candidate.id === flowId);
  if (!flow) throw new Error(`Unknown workflow flow: ${flowId}`);
  return flow;
}
